version: "3"
services:
  web:
    image: murphy2323/bmcs-tutorial:my-hello-world
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
  #    restart_policy:
  #      condition: on-failure
    ports:
      - "80:3000"
    networks:
      - webnet
networks:
  webnet:
